# Generated by Django 6.0.5 on 2026-05-20 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pressao_arterial', models.CharField(max_length=20)),
                ('horas_sono', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('glicemia', models.IntegerField(blank=True, null=True)),
                ('alimentacao', models.CharField(choices=[('sozinho', 'Sozinho'), ('com_auxilio', 'Com auxílio'), ('nao_realizou', 'Não realizou')], max_length=20)),
                ('locomocao', models.CharField(choices=[('sozinho', 'Sozinho'), ('com_auxilio', 'Com auxílio'), ('nao_realizou', 'Não realizou')], max_length=20)),
                ('transferencia', models.CharField(choices=[('sozinho', 'Sozinho'), ('com_auxilio', 'Com auxílio'), ('nao_realizou', 'Não realizou')], max_length=20)),
                ('banho', models.CharField(choices=[('sozinho', 'Sozinho'), ('com_auxilio', 'Com auxílio'), ('nao_realizou', 'Não realizou')], max_length=20)),
                ('vestir_se', models.CharField(choices=[('sozinho', 'Sozinho'), ('com_auxilio', 'Com auxílio'), ('nao_realizou', 'Não realizou')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
    ]
